GET http://localhost:8080/api/employees
Accept: application/json

###
GET http://localhost:8080/api/employees
Accept: application/xml

###
GET http://localhost:8080/api/employees?quantity=4
Accept: application/json

###
GET http://localhost:8080/api/employees/2
Accept: application/json

###
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "Wiesław Paleta",
  "region": "Warszawa",
  "dosh": 0.0
}

###
PUT http://localhost:8080/api/employees/6/addskill/Java

###
PUT http://localhost:8080/api/employees/6/payrise/1000.0

###
DELETE http://localhost:8080/api/employees/6

###
PUT http://localhost:8080/api/employees/6/promote